
/**
    - Projeto Lógico, Banco de Dados 1, 09/03/2018
    - Professor: Cláudio Baptista
    - Monitoria: Brunna Amorim
    - Identificador do Grupo: 10
    - Equipe:   Adriano Ribeiro,
                Agnaldo Junior,
                Dayvson Weslley,
                Rubens Batista,
                Matheus Melo,
                Wesley Anibal

    Descrição: Alterações em torno de DDL enviado em 21/12/2017 como parte da segunda fase do projeto.
**/


/* ACUDE */

	/* MELHOR LEGIBILIDADE */
	ALTER TABLE ACUDE RENAME COLUMN volumemaximo TO volume_maximo;
	ALTER TABLE ACUDE RENAME COLUMN comprimentro TO comprimento;

	/* ALTERACAO DE TIPO DE DADOS DE DECIMAL PARA REAL */
	ALTER TABLE ACUDE MODIFY (volume_maximo REAL, comprimento REAL, area REAL);

/* BACIA */

	/* ALTERACAO DE TIPO DE DADOS DE DECIMAL PARA REAL */
	ALTER TABLE BACIA MODIFY (area REAL, perimetro REAL);

/* BATIMETRIA */

	/* MELHOR LEGIBILIDADE */
	ALTER TABLE BATIMETRIA RENAME COLUMN data_2 TO data;
	ALTER TABLE BATIMETRIA RENAME COLUMN valorchuva TO valor_chuva;

	/* ALTERACAO DE TIPO DE DADOS DE DECIMAL PARA REAL */
	ALTER TABLE BATIMETRIA MODIFY valor_chuva REAL;

/* COTA_AREA_VOLUME */

	/* ALTERACAO DE TIPO DE DADOS DE DECIMAL PARA REAL */
	ALTER TABLE COTA_AREA_VOLUME MODIFY (cota REAL, area REAL, volume REAL);

/* E_DE_QUALIDADE */

	/* ANOMALIA NECESSARIA - EVITANDO ALTERAR A ESTRUTURA DA TABELA, A COLUNA 'M_QUALIDADE_ACD_ACUDE_ID' EH A MESMA DE 'M_QUALIDADE_ACD_ID',
	   DESSA FORMA, ELA PASSARA A ACEITAR VALORES NULL, MESMO SENDO CHAVE ESTRANGEIRA, E CONSEQUENTEMENTE INUTILIZADA NO PROJETO */
	ALTER TABLE E_DE_QUALIDADE MODIFY m_qualidade_acd_acude_id DECIMAL NULL;

	/* ALTERACAO DE TIPO DE DADOS DE DECIMAL PARA REAL, ASSIM COMO CHAVES ESTRANGEIRAS ACEITAREM VALOR NULL PARA FACILITAR INSERTS FUTUROS */
	ALTER TABLE E_DE_QUALIDADE MODIFY (m_qualidade_acd_id DECIMAL NULL, m_qualidade_rio_id DECIMAL NULL, latitude REAL, longitude REAL);

/* M_COTA_DIARIA */

	/* MELHOR LEGIBILIDADE */
	ALTER TABLE M_COTA_DIARIA RENAME COLUMN cotaatual TO cota_atual;
	ALTER TABLE M_COTA_DIARIA RENAME COLUMN data_2 TO data;

	/* ALTERACAO DE TIPO DE DADOS DE DECIMAL PARA REAL */
	ALTER TABLE M_COTA_DIARIA MODIFY (cota_atual REAL);

/* M_QUALIDADE_ACD */

	/* MELHOR LEGIBILIDADE */
	ALTER TABLE M_QUALIDADE_ACD RENAME COLUMN data_2 TO data;

	/* ALTERACAO DE TIPO DE DADOS DE DECIMAL PARA REAL E CAMPO DATA DE DECIMAL PARA DATE */
	ALTER TABLE M_QUALIDADE_ACD MODIFY (data DATE, ph REAL, dbo REAL, turbidez REAL, oxigenio REAL, alcalinidade REAL);

/* M_QUALIDADE_RIO */

	/* MELHOR LEGIBILIDADE */
	ALTER TABLE M_QUALIDADE_RIO RENAME COLUMN data_2 TO data;

	/* ALTERACAO DE TIPO DE DADOS DE DECIMAL PARA REAL */
	ALTER TABLE M_QUALIDADE_RIO MODIFY (ph REAL, dbo REAL, turbidez REAL, oxigenio REAL, alcalinidade REAL);

/* TELEFONES_USUARIO */
	
	/* ALTERACAO DE TIPO DE DADOS DE CHAR E VARCHAR PARA DECIMAL */
	ALTER TABLE TELEFONES_USUARIO MODIFY (ddd DECIMAL, numero DECIMAL);

/* USUARIO */

	/* ALTERACAO DO VARCHAR PARA 120 CARACTERES E NOME NAO PODERA SER NULL */
	ALTER TABLE USUARIO MODIFY (nome VARCHAR(120) NOT NULL);